export const productShowcaseData = {
  header: {
    title: "EXPLORE OUR PRODUCTS",
    subtitle: "Explore our most popular products across top categories, carefully selected to help you find what matters most.",
  },
  productCategories: {
    "Beauty & Personal Care": [
      {
        id: "12",
        name: "Lighted Makeup Mirror, 3000 mAh",
        price: "$39.95",
        rating: 4.4,
        badge: "",
        description: "Lighted Makeup Mirror, 3000 mAh Rechargeable Double Sided Magnifying Vanity Mirror with 3 Colors, 1x/10x, 360° Rotation , Brightness Adjustable Magnification Cosmetic Light up Mirror, Women Gift",
        image: "https://m.media-amazon.com/images/I/51586phz9fL._AC_SL1500_.jpg",
      },
      {
        id: "13",
        name: "Salmon DNA PDRN Anti-Aging Serum",
        price: "$33.99",
        rating: 4.8,
        badge: "",
        description: "Salmon DNA PDRN Anti-Aging Serum, 5000ppm Salmon Egg DNA Ampoule, 2000ppm Collagen",
        image: "https://m.media-amazon.com/images/I/71zYgOMplfL._SL1500_.jpg",
      },
      {
        id: "14",
        name: "Pure Daily Care NuDerma Handheld Skin Therapy Wand Machine",
        price: "$79.95",
        rating: 4.3,
        badge: "",
        description: "Pure Daily Care NuDerma Handheld Skin Therapy Wand Machine w/Neon – Anti-Aging - Skin Tightening - Wrinkle Reducing",
        image: "https://m.media-amazon.com/images/I/71gSdvj6mtL._AC_SL1500_.jpg",
      },
      {
        id: "15",
        name: "MelodySusie Professional Rechargeable",
        price: "$39.99",
        rating: 4.6,
        badge: "",
        description: "MelodySusie Professional Rechargeable Nail Drill 30000 RPM, Electric Nail File for Shaping, Removing & Polishing Gel Nails",
        image: "https://m.media-amazon.com/images/I/61nVWtO7fYL._SL1500_.jpg",
      },
      {
        id: "16",
        name: "DRMTLGY Brightening Eye Masks (30 Pairs)",
        price: "$44.00",
        rating: 4.3,
        badge: "",
        description: "DRMTLGY Brightening Eye Masks (30 Pairs) - Caffeine Eye Masks for Dark Circles and Puffiness with Hyaluronic Acid",
        image: "https://m.media-amazon.com/images/I/617IF4pGKaL._SL1500_.jpg",
      },
    ],
    "Health & HouseHold": [
      {
        id: "35",
        name: "Scotch-Brite Heavy Duty Scrub Sponge",
        price: "$8.72",
        rating: 4.8,
        badge: "Overall Pick",
        description: "9 heavy duty kitchen sponges designed for tough messes. Lasts 3X longer, ideal for cast iron skillets and outdoor grills.",
        image: "https://m.media-amazon.com/images/I/71e+sGSWJkL._AC_SX679_PIbundle-9,TopRight,0,0_SH20_.jpg",
      },
      {
        id: "36",
        name: "Scrubbing Bubbles Toilet Tablets",
        price: "$3.88",
        rating: 4.5,
        badge: "Amazon's Choice",
        description: "Continuous clean toilet drop-ins that help prevent stains and limescale buildup. Pack of 3.",
        image: "https://m.media-amazon.com/images/I/81R8edrtTHL._AC_SX679_.jpg",
      },
      {
        id: "37",
        name: "Unoutur Microfiber Wet Mop Pads",
        price: "$9.78",
        rating: 4.6,
        badge: "Amazon's Choice",
        description: "Reusable dry sweeping cloths compatible with Swiffer Sweeper Mop. 4PCS for hardwood surface cleaning.",
        image: "https://m.media-amazon.com/images/I/81KADKhfJuL._AC_SX679_.jpg",
      },
      {
        id: "38",
        name: "Amazon Basics Toilet Paper, 6 Rolls",
        price: "$6.31",
        rating: 4.4,
        badge: "Amazon's Choice",
        description: "FSC-certified 2-ply septic-safe toilet paper. Soft, 350 sheets per roll, 6 rolls = 37 regular rolls.",
        image: "https://m.media-amazon.com/images/I/71Mn+u69RbL._AC_SX679_PIbundle-6,TopRight,0,0_SH20_.jpg",
      },
      {
        id: "39",
        name: "Accelerator Energy Drink, Cherry Ice Pop",
        price: "$24.00",
        rating: 4.5,
        badge: "Amazon's Choice",
        description: "12oz can (12 pack), zero sugar. Sustained energy from 100% natural caffeine from green coffee bean & green tea extract.",
        image: "https://m.media-amazon.com/images/I/81xN6Nn4hML._AC_SX679_PIbundle-12,TopRight,0,0_SH20_.jpg",
      },
      {
        id: "40",
        name: "Waring Commercial Immersion Blender",
        price: "$1012.00",
        rating: 4.4,
        badge: "Amazon's Choice",
        description: "Heavy-duty stick immersion blender with 14\" removable shaft, 1 HP, 700W, variable speed. Professional restaurant kitchen grade.",
        image: "https://m.media-amazon.com/images/I/51swyaTQxPL._AC_SL1500_.jpg",
      }
    ],
    "Home Craft & HouseHolds": [
      {
        id: "19",
        name: "Food Kitchen Scale",
        price: "13.99",
        rating: 4.6,
        badge: "",
        description: "Etekcity Food Kitchen Scale, Digital Grams and Ounces for Weight Loss, Baking, Cooking, Keto and Meal Prep, LCD Display, Medium, 304 Stainless Steel",
        image: "https://m.media-amazon.com/images/I/91YrLTBnMcL._SL1500_.jpg",
      },
      {
        id: "20",
        name: "Zero Sugar Electrolytes",
        price: "$40.50",
        rating: 4.6,
        badge: "",
        description: "Drink LMNT Zero Sugar Electrolytes - Citrus Salt | Drink Mix | 30-Count",
        image: "https://m.media-amazon.com/images/I/81sZsv0qLIL._SL1500_.jpg",
      },
      {
        id: "21",
        name: "Paper Towels,",
        price: "$23.20",
        rating: 4.8,
        badge: "",
        description: "Bounty Quick Size Paper Towels, White, 8 Family Rolls = 20 Regular Rolls",
        image: "https://m.media-amazon.com/images/I/81+BZP2zUHL._AC_SL1500_.jpg",
      },
      {
        id: "22",
        name: "20 lb XL Heavyweight Picture Hanging Strips 16 Pairs",
        price: "$10.17",
        rating: 4.5,
        badge: "",
        description: "Command 20 lb XL Heavyweight Picture Hanging Strips 16 Pairs (32 Command Strips), Damage-Free Hanging Picture Hangers, Heavy Duty Wall Hanging Strips for...",
        image: "https://m.media-amazon.com/images/I/8172RgAY+DL._AC_SL1500_.jpg",
      },
      {
        id: "23",
        name: "Bug Zapper Outdoor, Mosquito Zapper,",
        price: "$35.99",
        rating: 4.4,
        badge: "",
        description: "GOOTOP Bug Zapper Outdoor, Mosquito Zapper, 3 Prong Plug in Electric Fly Zapper, Mosquito Killer, Fly Traps, Flying Insects Zapper Indoor Outdoor 90-130V, 4200V, ABS Plastic Outer (Black)",
        image: "https://m.media-amazon.com/images/I/71fATgj5scL._AC_SL1500_.jpg",
      }
    ],
    "Home & Kitchen": [
      {
        id: "6",
        name: "LUNINO Air Purifier",
        price: "$37.99",
        rating: 4.5,
        badge: "",
        description: "Air Purifier for Home Large Room up to 1200ft² with H13 True HEPA Filter, Air Quality Sensor, Sleep Mode, and Fragrance Function. Ideal for dust, smoke, and pet dander.",
        image: "https://m.media-amazon.com/images/I/71aamoHyRoL._AC_SX679_.jpg",
      },
      {
        id: "7",
        name: "Chef Preserve Vacuum Sealer",
        price: "$79.20",
        rating: 4.5,
        badge: "",
        description: "Compact vacuum sealer machine with 30 reusable bags. Powerful handheld design for food preservation and meal storage.",
        image: "https://m.media-amazon.com/images/I/71XEvtKF9oL._AC_SX679_.jpg",
      },
      {
        id: "8",
        name: "Hoover PowerScrub Carpet Cleaner",
        price: "$169.99",
        rating: 4.4,
        badge: "",
        description: "Deluxe carpet cleaner machine with multi-purpose tools for deep cleaning carpets and upholstery.",
        image: "https://m.media-amazon.com/images/I/712BlNJR10L._AC_SX679_.jpg",
      },
      {
        id: "9",
        name: "OTOTO Silicone Spoon Rest",
        price: "$9.95",
        rating: 4.5,
        badge: "Amazon's Choice",
        description: "Heat-resistant silicone utensil holder with non-slip design. Perfect for stove top organization.",
        image: "https://m.media-amazon.com/images/I/61TPuLYwdSL._AC_SX679_.jpg",
      },
      {
        id: "10",
        name: "EUREKA PowerSpeed Vacuum Cleaner",
        price: "$78.00",
        rating: 4.3,
        badge: "Amazon's Choice",
        description: "Lightweight upright vacuum cleaner with powerful suction for carpets and hard floors. Includes pet turbo tool.",
        image: "https://m.media-amazon.com/images/I/718xNJ75EIL._AC_SX679_.jpg",
      },
    ],
    "Sports & Outdoors": [
      {
        id: "24",
        name: "GlowCity Glow in The Dark Basketball",
        price: "$23.99",
        rating: 4.5,
        badge: "",
        description: "GlowCity Glow in The Dark Basketball - Sizes 5, 6, 7 Light Up Ball for Kids, Teens & Adults. Great for outdoor games and birthday gifts.",
        image: "https://m.media-amazon.com/images/I/71MDeI7trSL._AC_SX679_.jpg",
      },
      {
        id: "25",
        name: "Tailgating Pros Cornhole Boards",
        price: "$189.85",
        rating: 4.6,
        badge: "",
        description: "4'x2' lightweight cornhole boards set. Includes carrying case, 8 cornhole bags and tote for outdoor fun.",
        image: "https://m.media-amazon.com/images/I/919sMA5bs6L._AC_SX679_.jpg",
      },
      {
        id: "26",
        name: "Baden Elite Basketball",
        price: "$59.99",
        rating: 4.6,
        badge: "Amazon's Choice",
        description: "Premium quality composite basketball, ideal for indoor games. Available in youth, women's & men's sizes.",
        image: "https://m.media-amazon.com/images/I/81zNIGQqzXL._AC_SX679_.jpg",
      },
      {
        id: "27",
        name: "Portable Basketball Hoop",
        price: "$280.49",
        rating: 4.6,
        badge: "Amazon's Choice",
        description: "Adjustable height portable basketball hoop with rebounder. Perfect for home, driveway, or backyard play.",
        image: "https://m.media-amazon.com/images/I/61FFwBt2yKL._AC_SX679_.jpg",
      },
      {
        id: "28",
        name: "2 Pack Hand Warmers",
        price: "$9.99",
        rating: 4.4,
        badge: "Amazon's Choice",
        description: "Rechargeable electric hand warmers. Portable, reusable, and ideal for indoor/outdoor winter activities.",
        image: "https://m.media-amazon.com/images/I/61sTgTCuOiL._AC_SX679_.jpg",
      },
      {
        id: "29",
        name: "Nerf Vortex Aero Howler",
        price: "$14.99",
        rating: 4.8,
        badge: "Amazon's Choice",
        description: "Foam ball with long-distance flight tail and whistling sound. Fun indoor & outdoor toy, perfect for kids.",
        image: "https://m.media-amazon.com/images/I/715CoLzPhdL._AC_SX679_.jpg",
      },
    ],
    "Toys & Games": [
      {
        id: "1",
        name: "Bean Bag Toss Game for Kids",
        price: "$25.99",
        rating: 4.6,
        badge: "Amazon's Choice",
        description: "Fun outdoor and indoor bean bag toss game for kids. Perfect for parties and suitable for ages 3 to 8.",
        image: "https://m.media-amazon.com/images/I/81e74+LTdLL._AC_SX679_.jpg",
      },
      {
        id: "2",
        name: "Outdoor Kids Trampoline",
        price: "$229.99",
        rating: 4.2,
        badge: "Amazon's Choice",
        description: "Durable outdoor trampoline with safety enclosure net and foam padding. Built with rust-resistant steel frame.",
        image: "https://m.media-amazon.com/images/I/819do+9vicL._AC_SX679_.jpg",
      },
      {
        id: "3",
        name: "High-Speed Slot Car Race Track Set",
        price: "$49.99",
        rating: 3.3,
        badge: "",
        description: "Exciting racing track set with 2 cars and lap counter. Suitable for kids aged 6 to 12.",
        image: "https://m.media-amazon.com/images/I/816VWXVYSqL._AC_SX679_.jpg",
      },
      {
        id: "4",
        name: "Hasbro Connect 4 Game",
        price: "$8.89",
        rating: 4.8,
        badge: "Amazon's Choice",
        description: "Classic 2-player strategy board game. Connect 4 discs in a row to win. Great for family fun.",
        image: "https://m.media-amazon.com/images/I/81ZNRHJ+cIL._AC_SX679_.jpg",
      },
      {
        id: "5",
        name: "Candy Land Board Game",
        price: "$12.99",
        rating: 4.8,
        badge: "Amazon's Choice",
        description: "Classic kids board game with colorful adventures. Easy to play and ideal for ages 3 and up.",
        image: "https://m.media-amazon.com/images/I/71ZnGyItfoL._AC_SX679_.jpg",
      },
      {
        id: "6",
        name: "TEKFUN LCD Writing Tablet",
        price: "$13.64",
        rating: 4.5,
        badge: "Amazon's Choice",
        description: "10-inch LCD writing tablet for kids. Perfect for drawing, doodling, and learning without mess.",
        image: "https://m.media-amazon.com/images/I/71IbDDxz8iL._AC_SX679_.jpg",
      },
    ],
  },
};

export const PRODUCT_CATEGORIES = Object.keys(productShowcaseData.productCategories);
export const PRODUCTS_DATA = Object.entries(productShowcaseData.productCategories).flatMap(
  ([category, products]) => products.map((product) => ({ ...product, category }))
);
